### ISSUE TITLE
List of Barcodes

### ISSUE THREAD

**Issue by GoodbyeKittyy** [Gama-Tech/AK-Card-Scanner-Releases#1]
Hi there!

Thanks for your effort with emulating Animal Kaiser :)

I was wondering if there is a list of all the barcodes for the card scanner? Is there any ongoing project on this?

**Comment by Gama-Tech** [comment]
Hi! The barcodes were taken from this [Google doc ](https://docs.google.com/spreadsheets/d/1CbBiaGXh8Kiq20VubqkGdwByh6mY6jTwFGv_XPnkyVM/) and this [website ](https://ankaits.wordpress.com/2011/05/21/animal-kaiser-all-cards-barcodes).

**Comment by Gama-Tech** [comment]
Hi! The barcodes were taken from this [Google doc ](https://docs.google.com/spreadsheets/d/1CbBiaGXh8Kiq20VubqkGdwByh6mY6jTwFGv_XPnkyVM/) and this [website ](https://ankaits.wordpress.com/2011/05/21/animal-kaiser-all-cards-barcodes).
